// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QualityManager.Data;

#nullable disable

namespace QualityManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250222175350_Treshold")]
    partial class Treshold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QualityManager.Models.Codes.AnalysisType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AnalysisTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Microbiological Analysis"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Chemical Analysis"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Sensory Analysis"
                        });
                });

            modelBuilder.Entity("QualityManager.Models.Codes.ProcessStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProcessStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("QualityManager.Models.FoodAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnalysisTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProcessStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTypeId");

                    b.HasIndex("ProcessStatusId");

                    b.ToTable("FoodAnalyses");
                });

            modelBuilder.Entity("QualityManager.Models.Treshold", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnalysisTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("High")
                        .HasColumnType("bigint");

                    b.Property<long>("Low")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTypeId");

                    b.ToTable("Tresholds");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AnalysisTypeId = 1L,
                            High = 77777777L,
                            Low = 22222222L
                        },
                        new
                        {
                            Id = 2L,
                            AnalysisTypeId = 2L,
                            High = 7777777L,
                            Low = 2222222L
                        },
                        new
                        {
                            Id = 3L,
                            AnalysisTypeId = 3L,
                            High = 777777L,
                            Low = 222222L
                        });
                });

            modelBuilder.Entity("QualityManager.Models.FoodAnalysis", b =>
                {
                    b.HasOne("QualityManager.Models.Codes.AnalysisType", "AnalysisType")
                        .WithMany()
                        .HasForeignKey("AnalysisTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityManager.Models.Codes.ProcessStatus", "ProcessStatus")
                        .WithMany()
                        .HasForeignKey("ProcessStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisType");

                    b.Navigation("ProcessStatus");
                });

            modelBuilder.Entity("QualityManager.Models.Treshold", b =>
                {
                    b.HasOne("QualityManager.Models.Codes.AnalysisType", "AnalysisType")
                        .WithMany()
                        .HasForeignKey("AnalysisTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisType");
                });
#pragma warning restore 612, 618
        }
    }
}
