//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalysisMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalysisMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityManager.Resources.AnalysisMessages", typeof(AnalysisMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical components are within acceptable limits..
        /// </summary>
        public static string Chemical_inrange {
            get {
                return ResourceManager.GetString("Chemical_inrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical components are out of acceptable range..
        /// </summary>
        public static string Chemical_outrange {
            get {
                return ResourceManager.GetString("Chemical_outrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing complete:.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microorganisms are within limits..
        /// </summary>
        public static string Microbiological_inrange {
            get {
                return ResourceManager.GetString("Microbiological_inrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microorganisms are beyond acceptable limits..
        /// </summary>
        public static string Microbiological_outrange {
            get {
                return ResourceManager.GetString("Microbiological_outrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Peding {
            get {
                return ResourceManager.GetString("Peding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensory properties meet the required standards..
        /// </summary>
        public static string Sensory_inrange {
            get {
                return ResourceManager.GetString("Sensory_inrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensory properties do not meet the required standards..
        /// </summary>
        public static string Sensory_outrange {
            get {
                return ResourceManager.GetString("Sensory_outrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
